- git:
    repo: 'https://PLAYBOOK:GVuJBjgUhzR6NCg5m7yS@gitlab.arsn.dev/root/t_nsa_back.git'
    dest: '/var/www/gitlab-deployment/repos/'
    force: yes
    update: yes

- name: Downloading composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer
  tags: composer

- name: Installing composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer
  tags: composer

- name: Renaming composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer

- name: Making composer executable
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file

- name: Running composer installation
  shell: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  args:
    chdir: '/var/www/gitlab-deployment/repos/'

- name: Renaming .env.example
  shell:
    cmd: rm /var/www/gitlab-deployment/repos/.env.example
    warn: false

- name: Configuring nginx
  shell: mv /var/www/gitlab-deployment/repos/ansible/roles/Production/tasks/nginx.conf /etc/nginx/sites-available/default

- name: Running composer update
  shell: composer update -n
  args:
    chdir: '/var/www/gitlab-deployment/repos/'

- name: Running php artisan cache:clear
  shell: php artisan cache:clear
  args:
    chdir: '/var/www/gitlab-deployment/repos/'

- name: Chmod -R 777 storage
  shell: chmod -R 777 storage/
  args:
    chdir: '/var/www/gitlab-deployment/repos/'

- name: Running composer dump-autoload.
  shell: composer dump-autoload -n
  args:
    chdir: '/var/www/gitlab-deployment/repos/'

- name: Changing password variable in /var/www/gitlab-deployment/repos/ansible/roles/Production/files/.env.example
  lineinfile:
    regexp: DB_PASSWORD=
    line: "DB_PASSWORD={{ password }}"
    path: /var/www/gitlab-deployment/repos/ansible/roles/Production/files/.env.example
    state: present

- name: Copying new .env with password
  shell: cp /var/www/gitlab-deployment/repos/ansible/roles/Production/files/.env.example /var/www/gitlab-deployment/repos/.env

- name:  make migration
  shell: php artisan migrate
  args:
    chdir: '/var/www/gitlab-deployment/repos/'

- name:  make seed
  shell: php artisan db:seed
  args:
    chdir: '/var/www/gitlab-deployment/repos/'

- name: Restarting nginx
  service:
    name: nginx
    state: restarted
