- name: Install php & dependencies
  apt:
    name:
      - php
      - php-fpm
      - php-mbstring
      - php-pdo
      - php-mysql
      - php-xml
      - php-gd
      - php-curl
      - php-zip
      - curl
      - git
      - nginx-common
      - nginx
      - zip
      - unzip
    state: latest

- name: Reloading nginx
  service:
    name: nginx
    state: reloaded
