- git:
    repo: 'https://PLAYBOOK:Sz5mDtUAGq_dyqxViy6d@gitlab.arsn.dev/root/t_nsa_front.git'
    dest: '/var/www/gitlab-deployment/repos/'
    force: yes
    update: yes

- name: Install dependencies
  yarn:
    path: '/var/www/gitlab-deployment/repos/'

- name: Build project
  command: ng build --prod
  args:
    chdir: '/var/www/gitlab-deployment/repos/'

- name: Copy build to live directory
  shell: cp /var/www/gitlab-deployment/repos/dist/front/* /usr/share/nginx/html/

- name: Importing default sites-available
  shell: mv /var/www/gitlab-deployment/repos/ansible/roles/Nginx/tasks/default /etc/nginx/sites-available/

- name: Importing default sites-available
  shell: cp /var/www/gitlab-deployment/repos/dist/front/* /var/www/html

- name: Restarting nginx
  service:
    name: nginx
    state: restarted
