- name: Ensure MySQL packages are installed.
  apt:
    name:
      - 'default-mysql-server'
      - 'default-mysql-client'
      - 'python3-mysqldb'
      - 'python-mysqldb'
    state: present
  register: deb_mysql_install_packages

- name: Copying the configuration file.
  copy:
    src: mariadb.cnf
    dest: /etc/mysql/

- name: Checking if the database already exists.
  mysql_db:
    name: data
    state: present

- name: Creating the user "data".
  mysql_user:
    name: "data"
    password: "{{ password }}"
    host: '%'
    priv: "data.*:ALL,GRANT"
    state: present

- name: Restarting the service.
  service:
    name: mysqld
    state: restarted
